import fs from "node:fs/promises";
import path from "node:path";
import type { GlossConfig } from "@gloss/shared";
import { readAllTranslations } from "./fs.js";
import { flattenObject } from "./translationTree.js";

export type GenerateTypesOptions = {
  outFile?: string;
};

export type GenerateTypesResult = {
  outFile: string;
  keyCount: number;
};

const projectRoot = () => process.env.INIT_CWD || process.cwd();

const renderTypeFile = (keys: string[]) => {
  const keyUnion =
    keys.length === 0
      ? "never"
      : keys.map((key) => `  | ${JSON.stringify(key)}`).join("\n");

  return `/* This file is auto-generated by Gloss. Do not edit manually. */

export type I18nKey =
${keyUnion};

export type TranslateFn = (
  key: I18nKey,
  variables?: Record<string, string | number>,
) => string;

export type GlossI18nKey = I18nKey;
`;
};

export async function generateKeyTypes(
  cfg: GlossConfig,
  options: GenerateTypesOptions = {},
): Promise<GenerateTypesResult> {
  const data = await readAllTranslations(cfg);
  const keys = Array.from(
    new Set(
      Object.values(data).flatMap((tree) =>
        Object.keys(flattenObject((tree ?? {}) as Record<string, unknown>)),
      ),
    ),
  ).sort((left, right) => left.localeCompare(right));

  const outFile = path.resolve(projectRoot(), options.outFile ?? "i18n-keys.d.ts");
  const content = renderTypeFile(keys);
  await fs.writeFile(outFile, content, "utf8");

  return { outFile, keyCount: keys.length };
}
